FichaAcademia/Controllers/AlunosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FichaAcademia.AcessoDados;
using FichaAcademia.Dominio.Models;
using FichaAcademia.AcessoDados.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace FichaAcademia.Controllers
{
    [Authorize]
    public class AlunosController : Controller
    {
        private readonly IAlunoRepositorio _alunoRepositorio;
        private readonly IObjetivoRepositorio _objetivoRepositorio;
        private readonly IProfessorRepositorio _professorRepositorio;

        public AlunosController(IAlunoRepositorio alunoRepositorio, IObjetivoRepositorio objetivoRepositorio, IProfessorRepositorio professorRepositorio)
        {
            _alunoRepositorio = alunoRepositorio;
            _objetivoRepositorio = objetivoRepositorio;
            _professorRepositorio = professorRepositorio;
        }

        // GET: Alunos
        public async Task<IActionResult> Index()
        {            
            return View(await _alunoRepositorio.PegarTodos());
        } 

        public IActionResult Create()
        {
            ViewData["ObjetivoId"] = new SelectList(_objetivoRepositorio.PegarTodos(), "ObjetivoId", "Nome");
            ViewData["ProfessorId"] = new SelectList(_professorRepositorio.PegarTodos(), "ProfessorId", "Nome");
            return View();
        }
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AlunoId,NomeCompleto,Idade,Peso,ObjetivoId,ProfessorId,FrequenciaSemanal")] Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                await _alunoRepositorio.Inserir(aluno);
                return RedirectToAction(nameof(Index));
            }
            ViewData["ObjetivoId"] = new SelectList(_objetivoRepositorio.PegarTodos(), "ObjetivoId", "Nome", aluno.ObjetivoId);
            ViewData["ProfessorId"] = new SelectList(_professorRepositorio.PegarTodos(), "ProfessorId", "Nome", aluno.ProfessorId);
            return View(aluno);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var aluno = await _alunoRepositorio.PegarPeloId(id);
            if (aluno == null)
            {
                return NotFound();
            }
            ViewData["ObjetivoId"] = new SelectList(_objetivoRepositorio.PegarTodos(), "ObjetivoId", "Nome", aluno.ObjetivoId);
            ViewData["ProfessorId"] = new SelectList(_professorRepositorio.PegarTodos(), "ProfessorId", "Nome", aluno.ProfessorId);
            return View(aluno);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AlunoId,NomeCompleto,Idade,Peso,ObjetivoId,ProfessorId,FrequenciaSemanal")] Aluno aluno)
        {
            if (id != aluno.AlunoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _alunoRepositorio.Atualizar(aluno);
                return RedirectToAction(nameof(Index));
            }
            ViewData["ObjetivoId"] = new SelectList(_objetivoRepositorio.PegarTodos(), "ObjetivoId", "Nome", aluno.ObjetivoId);
            ViewData["ProfessorId"] = new SelectList(_professorRepositorio.PegarTodos(), "ProfessorId", "Nome", aluno.ProfessorId);
            return View(aluno);
        }

        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            await _alunoRepositorio.Excluir(id);
            return Json("Aluno excluído com sucesso");
        }

        public async Task<JsonResult> AlunoExiste (string NomeCompleto, int AlunoId)
        {
            if(AlunoId == 0)
            {
                if (await _alunoRepositorio.AlunoExiste(NomeCompleto))
                    return Json("Aluno já existe");

                return Json(true);
            }
            else
            {
                if (await _alunoRepositorio.AlunoExiste(NomeCompleto, AlunoId))
                    return Json("Aluno já existe");

                return Json(true);
            }
        }
    }
}

FichaAcademia/Controllers/ExerciciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FichaAcademia.AcessoDados;
using FichaAcademia.Dominio.Models;
using FichaAcademia.AcessoDados.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace FichaAcademia.Controllers
{    
    [Authorize]
    public class ExerciciosController : Controller
    {
        private readonly IExercicioRepositorio _exercicioRepositorio;
        private readonly ICategoriaExercicioRepositorio _categoriaExercicioRepositorio;
        private readonly IListaExercicioRepositorio _listaExercicioRepositorio;
        public ExerciciosController(IExercicioRepositorio exercicioRepositorio, ICategoriaExercicioRepositorio categoriaExercicioRepositorio, IListaExercicioRepositorio listaExercicioRepositorio)
        {
            _exercicioRepositorio = exercicioRepositorio;
            _categoriaExercicioRepositorio = categoriaExercicioRepositorio;
            _listaExercicioRepositorio = listaExercicioRepositorio;
        }

        // GET: Exercicios
        public async Task<IActionResult> Index()
        {
            
            return View(await _exercicioRepositorio.PegarTodos());
        }           

        public async Task<IActionResult> Listagem(int FichaId, int AlunoId)
        {
            ViewData["FichaId"] = FichaId;
            ViewData["AlunoId"] = AlunoId;

            return View(await _exercicioRepositorio.PegarTodos());
        }


        public async Task<IActionResult> AdicionarExercicio(int exercicioId, int frequencia, int repeticoes, int carga, int fichaId)
        {
            if (await _listaExercicioRepositorio.ExercicioExisteNaFicha(exercicioId, fichaId))
                return Json(false);

            ListaExercicio listaExercicio = new ListaExercicio
            {
                ExercicioId = exercicioId,
                Frequencia = frequencia,
                Repeticoes = repeticoes,
                Carga = carga,
                FichaId = fichaId
            };

            if (ModelState.IsValid)
            {
                await _listaExercicioRepositorio.Inserir(listaExercicio);
                return Json(true);
            }
            else return Json(false);
        }

               
        public async Task<IActionResult> Create()
        {
            ViewData["CategoriaExercicioId"] = new SelectList(_categoriaExercicioRepositorio.PegarTodos(), "CategoriaExercicioId", "Nome");
            return View();
        }

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ExercicioId,Nome,CategoriaExercicioId")] Exercicio exercicio)
        {
            if (ModelState.IsValid)
            {
                await _exercicioRepositorio.Inserir(exercicio);
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaExercicioId"] = new SelectList(_categoriaExercicioRepositorio.PegarTodos(), "CategoriaExercicioId", "Nome", exercicio.CategoriaExercicioId);
            return View(exercicio);
        }

      
        public async Task<IActionResult> Edit(int id)
        {     
            var exercicio = await _exercicioRepositorio.PegarPeloId(id);
            if (exercicio == null)
            {
                return NotFound();
            }
            ViewData["CategoriaExercicioId"] = new SelectList(_categoriaExercicioRepositorio.PegarTodos(), "CategoriaExercicioId", "Nome", exercicio.CategoriaExercicioId);
            return View(exercicio);
        }
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ExercicioId,Nome,CategoriaExercicioId")] Exercicio exercicio)
        {
            if (id != exercicio.ExercicioId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {   
                await _exercicioRepositorio.Atualizar(exercicio);
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriaExercicioId"] = new SelectList(_categoriaExercicioRepositorio.PegarTodos(), "CategoriaExercicioId", "Nome", exercicio.CategoriaExercicioId);
            return View(exercicio);
        }  
       
        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            await _exercicioRepositorio.Excluir(id);
            return Json("Exercício excluído com sucesso");
        }

        public async Task<JsonResult> ExercicioExiste(string nome, int ExercicioId)
        {
            if(ExercicioId == 0)
            {
                if (await _exercicioRepositorio.ExercicioExiste(nome))
                    return Json("Exercício já existe");

                return Json(true);
            }
            else
            {
                if(await _exercicioRepositorio.ExercicioExiste(nome, ExercicioId))
                    return Json("Exercício já existe");

                return Json(true);
            }
        }
    }
}

FichaAcademia/Controllers/FichasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FichaAcademia.AcessoDados;
using FichaAcademia.Dominio.Models;
using FichaAcademia.AcessoDados.Interfaces;
using Rotativa.AspNetCore;
using Microsoft.AspNetCore.Authorization;

namespace FichaAcademia.Controllers
{
    [Authorize]
    public class FichasController : Controller
    {
        private readonly IAlunoRepositorio _alunoRepositorio;
        private readonly IFichaRepositorio _fichaRepositorio;

        public FichasController(IAlunoRepositorio alunoRepositorio, IFichaRepositorio fichaRepositorio)
        {
            _alunoRepositorio = alunoRepositorio;
            _fichaRepositorio = fichaRepositorio;
        }

        // GET: Fichas
        public async Task<IActionResult> Index(int AlunoId)
        {
            ViewBag.AlunoId = AlunoId;
            return View(await _fichaRepositorio.PegarTodasFichasPeloAlunoId(AlunoId));
        }

        // GET: Fichas/Details/5
        public async Task<IActionResult> Details(int FichaId)
        {
            var ficha = await _fichaRepositorio.PegarFichaAlunoPeloId(FichaId);
            if (ficha == null)
            {
                return NotFound();
            }

            return View(ficha);
        }

        public async Task<IActionResult> VisualizarPDF(int FichaId)
        {
            var ficha = await _fichaRepositorio.PegarFichaAlunoPeloId(FichaId);
            if (ficha == null)
            {
                return NotFound();
            }

            return new ViewAsPdf("PDF", ficha) { FileName = "Ficha.PDF" };
        }

        public IActionResult Create(int AlunoId)
        {
            Ficha ficha = new Ficha();
            ficha.AlunoId = AlunoId;
            return View(ficha);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FichaId,Nome,Cadastro,Validade,AlunoId")] Ficha ficha)
        {
            ficha.Cadastro = DateTime.Parse(DateTime.Now.ToShortDateString());
            ficha.Validade = DateTime.Parse(DateTime.Now.AddYears(1).ToShortDateString());

            if (ModelState.IsValid)
            {
                await _fichaRepositorio.Inserir(ficha);
                return RedirectToAction(nameof(Index), new { AlunoId = ficha.AlunoId });
            }
            return View(ficha);
        }

        public async Task<IActionResult> Edit(int FichaId)
        {
            var ficha = await _fichaRepositorio.PegarPeloId(FichaId);
            if (ficha == null)
            {
                return NotFound();
            }

            return View(ficha);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int FichaId, [Bind("FichaId,Nome,Cadastro,Validade,AlunoId")] Ficha ficha)
        {
            if (FichaId != ficha.FichaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _fichaRepositorio.Atualizar(ficha);
                return RedirectToAction(nameof(Index), new { AlunoId = ficha.AlunoId });
            }

            return View(ficha);
        }

        [HttpPost]
        public async Task<JsonResult> Delete(int FichaId)
        {
            await _fichaRepositorio.Excluir(FichaId);
            return Json("Ficha excluída com sucesso");
        }

        public async Task<JsonResult> FichaExiste(string Nome, int FichaId)
        {
            if (FichaId == 0)
            {
                if (await _fichaRepositorio.FichaExiste(Nome))
                    return Json("Ficha já cadastrada");

                return Json(true);
            }
            else
            {
                if (await _fichaRepositorio.FichaExiste(Nome, FichaId))
                    return Json("Ficha já cadastrada");

                return Json(true);
            }
        }
    }
}

FichaAcademia/ViewComponents/DadosAlunoViewComponent.cs
using FichaAcademia.AcessoDados.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FichaAcademia.ViewComponents
{
    public class DadosAlunoViewComponent : ViewComponent
    {
        private readonly IAlunoRepositorio _alunoRepositorio;

        public DadosAlunoViewComponent(IAlunoRepositorio alunoRepositorio)
        {
            _alunoRepositorio = alunoRepositorio;
        }

        public async Task<IViewComponentResult> InvokeAsync(int AlunoId)
        {
            return View(await _alunoRepositorio.PegarDadosAlunoPeloId(AlunoId));
        }
    }
}

FichaAcademia/ViewComponents/ListagemExercicioFichaViewComponent.cs
using FichaAcademia.AcessoDados;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FichaAcademia.ViewComponents
{
    public class ListagemExercicioFichaViewComponent : ViewComponent
    {
        private readonly Contexto _contexto;

        public ListagemExercicioFichaViewComponent(Contexto contexto)
        {
            _contexto = contexto;
        }

        public async Task<IViewComponentResult> InvokeAsync(int FichaId)
        {
            return View(await _contexto.ListasExercicios.Include(l => l.Exercicio).Where(l => l.FichaId == FichaId).ToListAsync());
        }
    }
}

FichaAcademia/Views/Fichas/Create.cshtml
@model FichaAcademia.Dominio.Models.Ficha

@{
    ViewData["Title"] = "Nova ficha";
}

<div class="container">
    <div class="row">
        <div class="col s12">
            <div class="collection with-header">
                <h6 class="collection-header">Nova ficha</h6>
                <form asp-action="Create">
                    <div class="collection-item">
                        <div asp-validation-summary="ModelOnly" class="red-text darken-3"></div>
                        <div class="row">
                            <div class="input-field">
                                <input asp-for="Nome" class="validate" id="Nome" />
                                <label for="Nome">Nome</label>
                                <span asp-validation-for="Nome" class="red-text darken-3"></span>
                            </div>
                        </div>

                        <input asp-for="AlunoId" type="hidden" />
                        
                        <div class="collection-item">
                            <input type="submit" value="Salvar" class="btn-small teal darken-3" /> &nbsp;
                            <a asp-action="Index" asp-route-AlunoId="@Model.AlunoId" class="btn-small grey darken-1">Voltar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FichaAcademia/Views/Fichas/Details.cshtml
@model FichaAcademia.Dominio.Models.Ficha

@{
    ViewData["Title"] = "Detalhes da ficha " + Model.Nome;
}

<div class="collection">
    <div class="collection-item">
        @await  Component.InvokeAsync("DadosAluno", Model.AlunoId)
    </div>

    <div class="row collection-item">
        <div class="col s6">
            <p><strong>Cadastro : </strong>@Model.Cadastro</p>
        </div>

        <div class="col s6">
            <p><strong>Validade : </strong>@Model.Validade</p>
        </div>
    </div>
</div>

<div class="collection">
    <div class="collection-item">
        @await  Component.InvokeAsync("ListagemExercicioFicha", Model.FichaId)
    </div>
</div>

<a asp-controller="Fichas" asp-action="Index" asp-route-AlunoId="@Model.AlunoId">Voltar</a>

FichaAcademia/Views/Fichas/Edit.cshtml
@model FichaAcademia.Dominio.Models.Ficha

@{
    ViewData["Title"] = "Atualizar " + Model.Nome;
}

<div class="container">
    <div class="row">
        <div class="col s12">
            <div class="collection with-header">
                <h6 class="collection-header">Atualziar @Model.Nome</h6>
                <form asp-action="Edit">
                    <div class="collection-item">
                        <div asp-validation-summary="ModelOnly" class="red-text darken-3"></div>
                        <input type="hidden" asp-for="FichaId" />
                        <div class="row">
                            <div class="input-field">
                                <input asp-for="Nome" class="validate" id="Nome" />
                                <label for="Nome">Nome</label>
                                <span asp-validation-for="Nome" class="red-text darken-3"></span>
                            </div>
                        </div>

                        <input asp-for="AlunoId" type="hidden" />

                        <div class="collection-item">
                            <input type="submit" value="Atualizar" class="btn-small blue darken-3" /> &nbsp;
                            <a asp-action="Index" asp-route-AlunoId="@Model.AlunoId" class="btn-small grey darken-1">Voltar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FichaAcademia/Views/Fichas/Index.cshtml
@model IEnumerable<FichaAcademia.Dominio.Models.Ficha>

@{
    ViewData["Title"] = "Fichas cadastradas";
}

<h5>Fichas cadastradas</h5>

<p>
    <a asp-action="Create" asp-route-AlunoId="@ViewBag.AlunoId" class="btn-small green darken-2">Nova ficha</a>
</p>
<table class="table hover striped highlight centered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cadastro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Validade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Aluno)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cadastro)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Validade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Aluno.NomeCompleto)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-FichaId="@item.FichaId" class="btn-small light-blue darken-2">Atualizar</a> &nbsp;
                    <a asp-action="Details" asp-route-FichaId="@item.FichaId" class="btn-small amber darken-3">Detalhes</a> &nbsp;
                    <a asp-action="Listagem" asp-controller="Exercicios" asp-route-FichaId="@item.FichaId" asp-route-AlunoId="@item.AlunoId" class="btn-small blue-grey darken-1">Novo Exercicio</a>
                    <a asp-action="VisualizarPDF" asp-route-FichaId="@item.FichaId" class="btn-small red accent-4">PDF</a>
                    <a onclick="ExibirModal(@item.FichaId, '@item.Nome')" class="btn-small red darken-2">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<a asp-controller="Alunos" asp-action="Index">Voltar</a>


<div id="modal1" class="modal">
    <div class="modal-content">
        <h4>Confirmar exclusão</h4>
        <p>Deseja prosseguir com a exclusão de <b class="nome"></b> ?</p>
    </div>
    <div class="modal-footer">
        <a class="modal-close btn green accent-4">Não</a>
        <a class="modal-close btn red accent-4 btnConfirmar">Sim</a>
    </div>
</div>

@section Scripts
    {
    <script>
        $(document).ready(function () {
            $(".modal").modal();
        })

        function ExibirModal(FichaId, nome) {
            $(".nome").html(nome);

            $("#modal1").modal("open");

            $(".btnConfirmar").on('click', function () {
                $.ajax({
                    method: "POST",
                    url: "/Fichas/Delete",
                    data: { FichaId: FichaId },
                    success: function () {
                        location.reload();
                    }
                });
            });
        }
    </script>
}

FichaAcademia/Views/Fichas/PDF.cshtml
@model FichaAcademia.Dominio.Models.Ficha

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <title>PDF</title>
</head>
<body>
    <div class="collection">
        <div class="collection-item">
            @await Component.InvokeAsync("DadosAluno", Model.AlunoId)
        </div>

        <div class="row collection-item">
            <div class="col s6">
                <p><strong>Cadastro : </strong>@Model.Cadastro</p>
            </div>

            <div class="col s6">
                <p><strong>Validade : </strong>@Model.Validade</p>
            </div>
        </div>
    </div>

    <div class="collection">
        <div class="collection-item">
            @await Component.InvokeAsync("ListagemExercicioFicha", Model.FichaId)
        </div>
    </div>
</body>
</html>